### ISSUE TITLE
Sumokoin GUI Wallet not synchronizing

### ISSUE THREAD

**Issue by aekonet** [sumoprojects/sumokoin#111]
After fork at block 116520 my wallet didn't synchronize anymore.
I donwloaded current version: v0.0.3, installed and started, but still the synchronizing stucks (since hours) at block 116521 (at 99%). Restarting didn't change anything.
Could somebody help or check issue?

**Comment by quangvu3** [comment]
1. Make sure to exit your wallet first

2. Go to `~/sumokoin` directory (on Mac, Linux) or `C:\ProgramData\sumokoin` (on Windows), delete file `p2pstate.bin` so that it can refresh connection to valid nodes

**Comment by aekonet** [comment]
Many thanks for your hint.
Exit wallet, deleted file, but up to now still identical problem (stuck at 116521)

![image](https://user-images.githubusercontent.com/38100662/38362581-b0343c04-38d1-11e8-89f9-bf290ad4aa2f.png)

How long could this last?
Or is there another solution?

**Comment by quangvu3** [comment]
Better restart Windows and continue with (2) step

**Comment by aekonet** [comment]
Done, but unfortunately remains the same (up to now)
Is it possible to delete the database, so that Wallet is forced to load it new?

**Comment by aekonet** [comment]
I removed lmdb directory now, after restart wallet seems to synchronize from scratch, but will need hours :)

![image](https://user-images.githubusercontent.com/38100662/38367568-5462855e-38e3-11e8-9c12-5d7f0e346e7a.png)

**Comment by aekonet** [comment]
Working, full sychronized.
BR

**Comment by quangvu3** [comment]
All right. So, it could be due to database corruption. Can you pls close this issue?

**Comment by mannie65** [comment]
I have deleted both the o2o file and lmdb with latest Windows wallet with no luck - still get stucks at 116522

**Comment by aekonet** [comment]
@quangvu3: 
Seems to be still a problem for mannie65, better to keep issue open for the time being?

**Comment by quangvu3** [comment]
I would appreciate you guys if you can run daemon from command line to see what reported while it gets stuck.

You can find the deamon exe (`sumokoind`) at `Resouces\bin` of installed folder (`C:\Program Files\Sumokoin GUI Wallet` for Windows x64)

**Comment by mannie65** [comment]
@quangvu3 - OK -  I have started the deamon manually and will report back once it reaches that height

**Comment by mannie65** [comment]
OK - so the deamon basically halts at block 116522 and reckons it synced 

![image](https://user-images.githubusercontent.com/33869840/38427502-4efae11e-39b1-11e8-8448-2d9f8219bafc.png)



SYNCHRONIZATION started
2018-Apr-06 15:19:06.065596 [P2P9][67.172.20.79:19733 OUT]Sync data returned a new top block candidate: 116520 -> 117110 [Your node is 590 blocks (1 days) behind]
SYNCHRONIZATION started
2018-Apr-06 15:19:06.857701 [P2P1][172.89.0.206:19733 OUT]Sync data returned a new top block candidate: 116520 -> 116522 [Your node is 2 blocks (0 days) behind]
SYNCHRONIZATION started
2018-Apr-06 15:19:10.528597 [P2P9][172.89.0.206:19733 OUT]Synced 116522/116522
2018-Apr-06 15:19:10.529096 [P2P9][172.89.0.206:19733 OUT] SYNCHRONIZED OK

**Comment by mannie65** [comment]
Guys just and FYI - I ended up moving my wallet to Android and importing it - so I now have access to my  new coins post fork, didn't resolve the issues above, so I am not sure if others will get it.

**Comment by bryster99** [comment]
I have been experiencing the exact same symptom for about a week and have not had time until now to sit down and start looking at it. Sumokoind does not sync beyond block 116522 for me. I have deleted the database and started from scratch, but still only reach 116522 and hang. 

Any more help on this?

**Comment by bryster99** [comment]
Here is the log from today after a clean reboot and deleting the p2pstate.bin file:

[2018-04-10 08:57:27,430] [INFO] [sumokoind] started
[2018-04-10 08:57:27,767] [INFO] [sumokoind]>>> Creating the logger system
[2018-04-10 08:57:27,796] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:27.796577 Initializing cryptonote protocol...
[2018-04-10 08:57:27,796] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:27.796577 Cryptonote protocol initialized OK
[2018-04-10 08:57:27,796] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:27.797578 Initializing p2p server...
[2018-04-10 08:57:29,585] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:29.585818 Number of seed nodes: 5
[2018-04-10 08:57:29,586] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:29.586815 Set limit-up to 2048 kB/s
[2018-04-10 08:57:29,588] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:29.586815 Set limit-down to 8192 kB/s
[2018-04-10 08:57:29,588] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:29.586815 Set limit-up to 2048 kB/s
[2018-04-10 08:57:29,588] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:29.586815 Set limit-down to 8192 kB/s
[2018-04-10 08:57:29,589] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:29.586815 Binding on 0.0.0.0:19733
[2018-04-10 08:57:29,591] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:29.586815 Net service bound to 0.0.0.0:19733
[2018-04-10 08:57:29,592] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:29.586815 Attempting to add IGD port mapping.
[2018-04-10 08:57:34,318] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:34.318809 UPnP device was found but not recognized as IGD.
[2018-04-10 08:57:34,319] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:34.318809 P2p server initialized OK
[2018-04-10 08:57:34,319] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:34.318809 Initializing core rpc server...
[2018-04-10 08:57:34,319] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:34.318809 Binding on 127.0.0.1:19734
[2018-04-10 08:57:34,321] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:34.318809 Core rpc server initialized OK on port: 19734
[2018-04-10 08:57:34,322] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:34.318809 Initializing core...
[2018-04-10 08:57:34,365] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:34.365870 Locking C:\ProgramData\sumokoin\.daemon_lock
[2018-04-10 08:57:34,365] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:34.365870 Loading blockchain from folder C:\ProgramData\sumokoin\lmdb ...
[2018-04-10 08:57:34,365] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:34.365870 option: fast
[2018-04-10 08:57:34,367] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:34.365870 option: async
[2018-04-10 08:57:34,367] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:34.365870 option: 1000
[2018-04-10 08:57:34,378] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:34.377874 DB map size:     9663676416
[2018-04-10 08:57:34,378] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:34.377874 Space used:      7542702080
[2018-04-10 08:57:34,378] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:34.377874 Space remaining: 2120974336
[2018-04-10 08:57:34,378] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:34.378853 Size threshold:  0
[2018-04-10 08:57:34,380] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:34.378853 Percent used: 0.7805  Percent threshold: 0.8000
[2018-04-10 08:57:34,440] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:34.439923 reorganizing from 106443
[2018-04-10 08:57:41,250] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:41.251280 reorganization done
[2018-04-10 08:57:41,262] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:41.262354 Blockchain initialized. last block: 116521, d5.h16.m8.s47 time ago, current difficulty: 480000000
[2018-04-10 08:57:41,263] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:41.262354 Blockchain checkpoints file not found
[2018-04-10 08:57:42,157] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.158582 [check_and_resize_for_batch] checking DB size
[2018-04-10 08:57:42,160] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.158582 DB map size:     9663676416
[2018-04-10 08:57:42,161] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.158582 Space used:      7542702080
[2018-04-10 08:57:42,161] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.158582 Space remaining: 2120974336
[2018-04-10 08:57:42,164] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.158582 Size threshold:  0
[2018-04-10 08:57:42,164] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.158582 Percent used: 0.7805  Percent threshold: 0.8000
[2018-04-10 08:57:42,244] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.245841 CHECKPOINT PASSED FOR HEIGHT 5000 
[2018-04-10 08:57:42,255] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.255891 CHECKPOINT PASSED FOR HEIGHT 10000 <360b96c3d0a5202c548672d550700d982ca15ad5627f70bce0a89dda840b3611>
[2018-04-10 08:57:42,267] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.267121 CHECKPOINT PASSED FOR HEIGHT 15000 <94c86b344fe2765727067997f45ca289b71ce9279ecc245c8216f94fdefb33bc>
[2018-04-10 08:57:42,276] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.277143 CHECKPOINT PASSED FOR HEIGHT 21300 
[2018-04-10 08:57:42,279] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.277143 [check_and_resize_for_batch] checking DB size
[2018-04-10 08:57:42,279] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.277143 DB map size:     9663676416
[2018-04-10 08:57:42,280] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.277143 Space used:      7542702080
[2018-04-10 08:57:42,282] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.277143 Space remaining: 2120974336
[2018-04-10 08:57:42,283] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.277143 Size threshold:  0
[2018-04-10 08:57:42,285] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.277143 Percent used: 0.7805  Percent threshold: 0.8000
[2018-04-10 08:57:42,286] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.287102 CHECKPOINT PASSED FOR HEIGHT 1 <82e8f378ea29d152146b6317903249751b809e97c0b6655f86e120b9de95c38a>
[2018-04-10 08:57:42,289] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.287102 CHECKPOINT PASSED FOR HEIGHT 10 
[2018-04-10 08:57:42,289] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.287102 CHECKPOINT PASSED FOR HEIGHT 100 
[2018-04-10 08:57:42,292] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.293193 CHECKPOINT PASSED FOR HEIGHT 1000 
[2018-04-10 08:57:42,303] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.303200 CHECKPOINT PASSED FOR HEIGHT 3000 <81e040955b710dc5a5056668c4eaf3fbc4da2f72c0a63763250ede32a92e0f06>
[2018-04-10 08:57:42,305] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.303200 CHECKPOINT PASSED FOR HEIGHT 5000 
[2018-04-10 08:57:42,305] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.303200 CHECKPOINT PASSED FOR HEIGHT 10000 <360b96c3d0a5202c548672d550700d982ca15ad5627f70bce0a89dda840b3611>
[2018-04-10 08:57:42,308] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.303200 CHECKPOINT PASSED FOR HEIGHT 15000 <94c86b344fe2765727067997f45ca289b71ce9279ecc245c8216f94fdefb33bc>
[2018-04-10 08:57:42,311] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.310202 CHECKPOINT PASSED FOR HEIGHT 20000 <603a45b60dd92ef4524c80d58411d09480b4668c54bc08dd651d838832bd399e>
[2018-04-10 08:57:42,313] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.313261 CHECKPOINT PASSED FOR HEIGHT 20251 <08f1086be149c18dece35b5bf0220aeb3ff8c5f01192838db8ca5a685f42d041>
[2018-04-10 08:57:42,328] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.327359 CHECKPOINT PASSED FOR HEIGHT 50000 
[2018-04-10 08:57:42,341] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.341630 CHECKPOINT PASSED FOR HEIGHT 75000 
[2018-04-10 08:57:42,348] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.349642 CHECKPOINT PASSED FOR HEIGHT 100000 
[2018-04-10 08:57:42,354] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.353659 CHECKPOINT PASSED FOR HEIGHT 116134 
[2018-04-10 08:57:42,355] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.354605 Core initialized OK
[2018-04-10 08:57:42,355] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.354605 Starting core rpc server...
[2018-04-10 08:57:42,357] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.354605 Run net_service loop( 4 threads)...
[2018-04-10 08:57:42,358] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.355607 [SRV_MAIN]Core rpc server started ok
[2018-04-10 08:57:42,361] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.355607 [SRV_MAIN]Starting p2p net loop...
[2018-04-10 08:57:42,364] [INFO] [sumokoind]>>> MARK   {2} {p1} 2018-04-10 08:57:42.355607 [abstract_tcp_server2.inl+271 ::save_dbg_log]  connection type RPC 127.0.0.1:19734 <--> 127.0.0.1:3481
[2018-04-10 08:57:42,365] [INFO] [sumokoind]>>> 
[2018-04-10 08:57:42,365] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:42.356606 [SRV_MAIN]Run net_service loop( 10 threads)...
[2018-04-10 08:57:42,367] [INFO] [sumokoind]>>> MARK   {3} {p1} 2018-04-10 08:57:42.357609 [abstract_tcp_server2.inl+271 ::save_dbg_log]  connection type RPC 127.0.0.1:19734 <--> 127.0.0.1:3482
[2018-04-10 08:57:42,368] [INFO] [sumokoind]>>> 
[2018-04-10 08:57:43,357] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:43.357568 [P2P7]
[2018-04-10 08:57:43,358] [INFO] [sumokoind]>>> **********************************************************************
[2018-04-10 08:57:43,359] [INFO] [sumokoind]>>> The daemon will start synchronizing with the network. It may take up to several hours.
[2018-04-10 08:57:43,361] [INFO] [sumokoind]>>> 
[2018-04-10 08:57:43,361] [INFO] [sumokoind]>>> You can set the level of process detailization* through "set_log " command*, where  is between 0 (no details) and 4 (very verbose).
[2018-04-10 08:57:43,362] [INFO] [sumokoind]>>> 
[2018-04-10 08:57:43,364] [INFO] [sumokoind]>>> Use "help" command to see the list of available commands.
[2018-04-10 08:57:43,365] [INFO] [sumokoind]>>> 
[2018-04-10 08:57:43,367] [INFO] [sumokoind]>>> Note: in case you need to interrupt the process, use "exit" command. Otherwise, the current progress won't be saved.
[2018-04-10 08:57:43,368] [INFO] [sumokoind]>>> **********************************************************************
[2018-04-10 08:57:43,368] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:43.357568 [P2P8]Connecting to 107.191.61.96:19733(white=1, last_seen: never)...
[2018-04-10 08:57:43,369] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:43.357568 [P2P7]Tx <6d310377cb087729eb9c68faa09f44de824551a9cd5fdef17edaedaa651668c0> removed from tx pool due to outdated, age: 135878
[2018-04-10 08:57:43,473] [INFO] [sumokoind]>>> MARK   {4} {p1} 2018-04-10 08:57:43.474869 [abstract_tcp_server2.inl+271 ::save_dbg_log]  connection type P2P 10.100.1.113:3485 <--> 107.191.61.96:19733
[2018-04-10 08:57:43,476] [INFO] [sumokoind]>>> 
[2018-04-10 08:57:43,825] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:43.826782 [P2P9][107.191.61.96:19733 OUT] COMMAND_HANDSHAKE(AND CLOSE) INVOKED OK
[2018-04-10 08:57:43,826] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:43.826782 [P2P8]Connecting to 99.198.136.252:19733(white=0, last_seen: d0.h0.m0.s17)...
[2018-04-10 08:57:43,828] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:43.827786 [P2P7]Failed to invoke command 1007 return code -3
[2018-04-10 08:57:43,828] [ERROR] [sumokoind]>>> 2018-Apr-10 08:57:43.827786 [P2P7][107.191.61.96:19733 OUT]COMMAND_REQUEST_SUPPORT_FLAGS invoke failed. (-3, LEVIN_ERROR_CONNECTION_DESTROYED)
[2018-04-10 08:57:43,882] [INFO] [sumokoind]>>> MARK   {4} {p1} 2018-04-10 08:57:43.882850 [abstract_tcp_server2.inl+271 ::save_dbg_log]  connection type P2P 10.100.1.113:3486 <--> 99.198.136.252:19733
[2018-04-10 08:57:43,884] [INFO] [sumokoind]>>> 
[2018-04-10 08:57:43,989] [INFO] [sumokoind]>>> MARK   {3} {p1} 2018-04-10 08:57:43.988899 [abstract_tcp_server2.inl+271 ::save_dbg_log]  connection type RPC 127.0.0.1:19734 <--> 127.0.0.1:3487
[2018-04-10 08:57:43,990] [INFO] [sumokoind]>>> 
[2018-04-10 08:57:44,322] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:44.322160 [P2P7][99.198.136.252:19733 OUT]Sync data returned a new top block candidate: 116522 -> 118519 [Your node is 1997 blocks (5 days) behind]
[2018-04-10 08:57:44,322] [INFO] [sumokoind]>>> SYNCHRONIZATION started
[2018-04-10 08:57:44,323] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:44.322160 [P2P7]Remote blockchain height: 118519, id: <0f8d988dd01e76bcd7de3b6a67df6dcee4a321d2ec1dd54e793b814bd28e41cf>
[2018-04-10 08:57:44,323] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:44.322160 [P2P7][99.198.136.252:19733 OUT] COMMAND_HANDSHAKE INVOKED OK
[2018-04-10 08:57:44,325] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:44.323137 [P2P8]Connecting to 45.63.17.239:19733(white=0, last_seen: d0.h0.m0.s13)...
[2018-04-10 08:57:44,408] [INFO] [sumokoind]>>> MARK   {4} {p1} 2018-04-10 08:57:44.409196 [abstract_tcp_server2.inl+271 ::save_dbg_log]  connection type P2P 10.100.1.113:3488 <--> 45.63.17.239:19733
[2018-04-10 08:57:44,410] [INFO] [sumokoind]>>> 
[2018-04-10 08:57:44,707] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:44.707435 [P2P9][45.63.17.239:19733 OUT]Sync data returned a new top block candidate: 116522 -> 118519 [Your node is 1997 blocks (5 days) behind]
[2018-04-10 08:57:44,707] [INFO] [sumokoind]>>> SYNCHRONIZATION started
[2018-04-10 08:57:44,709] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:44.707435 [P2P9]Remote blockchain height: 118519, id: <0f8d988dd01e76bcd7de3b6a67df6dcee4a321d2ec1dd54e793b814bd28e41cf>
[2018-04-10 08:57:44,709] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:44.707435 [P2P9][45.63.17.239:19733 OUT] COMMAND_HANDSHAKE INVOKED OK
[2018-04-10 08:57:44,710] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:44.708412 [P2P8]Connecting to 88.99.41.3:19733(white=0, last_seen: d0.h0.m0.s13)...
[2018-04-10 08:57:44,869] [INFO] [sumokoind]>>> MARK   {4} {p1} 2018-04-10 08:57:44.870551 [abstract_tcp_server2.inl+271 ::save_dbg_log]  connection type P2P 10.100.1.113:3489 <--> 88.99.41.3:19733
[2018-04-10 08:57:44,871] [INFO] [sumokoind]>>> 
[2018-04-10 08:57:48,500] [INFO] [sumokoind]>>> MARK   {3} {p1} 2018-04-10 08:57:48.500812 [abstract_tcp_server2.inl+271 ::save_dbg_log]  connection type RPC 127.0.0.1:19734 <--> 127.0.0.1:3497
[2018-04-10 08:57:48,502] [INFO] [sumokoind]>>> 
[2018-04-10 08:57:49,997] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:49.997670 [P2P5][88.99.41.3:19733 OUT]Sync data returned a new top block candidate: 116522 -> 118519 [Your node is 1997 blocks (5 days) behind]
[2018-04-10 08:57:50,000] [INFO] [sumokoind]>>> SYNCHRONIZATION started
[2018-04-10 08:57:50,002] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:49.997670 [P2P5]Remote blockchain height: 118519, id: <0f8d988dd01e76bcd7de3b6a67df6dcee4a321d2ec1dd54e793b814bd28e41cf>
[2018-04-10 08:57:50,003] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:49.998674 [P2P5][88.99.41.3:19733 OUT] COMMAND_HANDSHAKE INVOKED OK
[2018-04-10 08:57:50,003] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:49.999675 [P2P8]Connecting to 45.77.91.22:19733(white=0, last_seen: d0.h0.m0.s6)...
[2018-04-10 08:57:50,154] [INFO] [sumokoind]>>> MARK   {4} {p1} 2018-04-10 08:57:50.154291 [abstract_tcp_server2.inl+271 ::save_dbg_log]  connection type P2P 10.100.1.113:3498 <--> 45.77.91.22:19733
[2018-04-10 08:57:50,155] [INFO] [sumokoind]>>> 
[2018-04-10 08:57:54,155] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:54.156668 [P2P7][45.63.17.239:19733 OUT]-->>NOTIFY_REQUEST_GET_OBJECTS: blocks.size()=10, txs.size()=0requested blocks count=10 / 10
[2018-04-10 08:57:54,157] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:54.158669 [P2P3][88.99.41.3:19733 OUT]-->>NOTIFY_REQUEST_GET_OBJECTS: blocks.size()=10, txs.size()=0requested blocks count=10 / 10
[2018-04-10 08:57:54,158] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:54.158669 [P2P6][99.198.136.252:19733 OUT]-->>NOTIFY_REQUEST_GET_OBJECTS: blocks.size()=10, txs.size()=0requested blocks count=10 / 10
[2018-04-10 08:57:54,492] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:54.491853 [P2P9][45.77.91.22:19733 OUT]Sync data returned a new top block candidate: 116522 -> 118519 [Your node is 1997 blocks (5 days) behind]
[2018-04-10 08:57:54,493] [INFO] [sumokoind]>>> SYNCHRONIZATION started
[2018-04-10 08:57:54,493] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:54.491853 [P2P9]Remote blockchain height: 118519, id: <0f8d988dd01e76bcd7de3b6a67df6dcee4a321d2ec1dd54e793b814bd28e41cf>
[2018-04-10 08:57:54,496] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:54.491853 [P2P9][45.77.91.22:19733 OUT] COMMAND_HANDSHAKE INVOKED OK
[2018-04-10 08:57:54,496] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:54.492853 [P2P8]Connecting to 65.30.48.125:19733(white=0, last_seen: d0.h0.m0.s43)...
[2018-04-10 08:57:54,565] [INFO] [sumokoind]>>> MARK   {4} {p1} 2018-04-10 08:57:54.565199 [abstract_tcp_server2.inl+271 ::save_dbg_log]  connection type P2P 10.100.1.113:3502 <--> 65.30.48.125:19733
[2018-04-10 08:57:54,565] [INFO] [sumokoind]>>> 
[2018-04-10 08:57:54,765] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:54.764713 [P2P4][65.30.48.125:19733 OUT]Sync data returned a new top block candidate: 116522 -> 118519 [Your node is 1997 blocks (5 days) behind]
[2018-04-10 08:57:54,766] [INFO] [sumokoind]>>> SYNCHRONIZATION started
[2018-04-10 08:57:54,766] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:54.764713 [P2P4]Remote blockchain height: 118519, id: <0f8d988dd01e76bcd7de3b6a67df6dcee4a321d2ec1dd54e793b814bd28e41cf>
[2018-04-10 08:57:54,767] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:54.764713 [P2P4][65.30.48.125:19733 OUT] COMMAND_HANDSHAKE INVOKED OK
[2018-04-10 08:57:54,769] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:54.766712 [P2P8]Connecting to 173.19.192.56:19733(white=0, last_seen: d0.h0.m0.s4)...
[2018-04-10 08:57:54,770] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:54.768744 [P2P4][99.198.136.252:19733 OUT]Got NEW BLOCKS inside of handle_response_get_objects: size: 10
[2018-04-10 08:57:54,772] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:54.768744 [P2P4]block_batches: 2
[2018-04-10 08:57:54,773] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:54.768744 [P2P4]Skipping prepare blocks. New blocks don't belong to chain.
[2018-04-10 08:57:54,815] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:54.815775 [P2P4]Block with id: 
[2018-04-10 08:57:54,816] [INFO] [sumokoind]>>>  for alternative chain, does not have enough proof of work: 
[2018-04-10 08:57:54,818] [INFO] [sumokoind]>>>  expected difficulty: 5283587651
[2018-04-10 08:57:54,819] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:54.815775 [P2P4][99.198.136.252:19733 OUT]Block verification failed, dropping connection
[2018-04-10 08:57:54,819] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:54.815775 [P2P4]IP 99.198.136.252 fail score=1
[2018-04-10 08:57:54,878] [INFO] [sumokoind]>>> MARK   {4} {p1} 2018-04-10 08:57:54.877995 [abstract_tcp_server2.inl+271 ::save_dbg_log]  connection type P2P 10.100.1.113:3503 <--> 173.19.192.56:19733
[2018-04-10 08:57:54,878] [INFO] [sumokoind]>>> 
[2018-04-10 08:57:55,065] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:55.065485 [P2P4][45.63.17.239:19733 OUT]Got NEW BLOCKS inside of handle_response_get_objects: size: 10
[2018-04-10 08:57:55,066] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:55.065485 [P2P4]block_batches: 2
[2018-04-10 08:57:55,068] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:55.065485 [P2P4]Skipping prepare blocks. New blocks don't belong to chain.
[2018-04-10 08:57:55,109] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:55.109515 [P2P4]Block with id: 
[2018-04-10 08:57:55,111] [INFO] [sumokoind]>>>  for alternative chain, does not have enough proof of work: 
[2018-04-10 08:57:55,111] [INFO] [sumokoind]>>>  expected difficulty: 5283587651
[2018-04-10 08:57:55,112] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:55.109515 [P2P4][45.63.17.239:19733 OUT]Block verification failed, dropping connection
[2018-04-10 08:57:55,114] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:55.109515 [P2P4]IP 45.63.17.239 fail score=1
[2018-04-10 08:57:55,124] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:55.123525 [P2P7][65.30.48.125:19733 OUT]-->>NOTIFY_REQUEST_GET_OBJECTS: blocks.size()=10, txs.size()=0requested blocks count=10 / 10
[2018-04-10 08:57:55,128] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:55.128529 [P2P9][45.77.91.22:19733 OUT]-->>NOTIFY_REQUEST_GET_OBJECTS: blocks.size()=10, txs.size()=0requested blocks count=10 / 10
[2018-04-10 08:57:55,710] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:55.710160 [P2P7][65.30.48.125:19733 OUT]Got NEW BLOCKS inside of handle_response_get_objects: size: 10
[2018-04-10 08:57:55,711] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:55.710160 [P2P7]block_batches: 2
[2018-04-10 08:57:55,713] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:55.710160 [P2P7]Skipping prepare blocks. New blocks don't belong to chain.
[2018-04-10 08:57:55,759] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:55.759193 [P2P7]Block with id: 
[2018-04-10 08:57:55,760] [INFO] [sumokoind]>>>  for alternative chain, does not have enough proof of work: 
[2018-04-10 08:57:55,762] [INFO] [sumokoind]>>>  expected difficulty: 5283587651
[2018-04-10 08:57:55,763] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:55.760195 [P2P7][65.30.48.125:19733 OUT]Block verification failed, dropping connection
[2018-04-10 08:57:55,765] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:55.760195 [P2P7]IP 65.30.48.125 fail score=1
[2018-04-10 08:57:57,494] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:57.495410 [P2P9][45.77.91.22:19733 OUT]Got NEW BLOCKS inside of handle_response_get_objects: size: 10
[2018-04-10 08:57:57,496] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:57.495410 [P2P9]block_batches: 2
[2018-04-10 08:57:57,497] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:57.495410 [P2P9]Skipping prepare blocks. New blocks don't belong to chain.
[2018-04-10 08:57:57,538] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:57.538442 [P2P9]Block with id: 
[2018-04-10 08:57:57,539] [INFO] [sumokoind]>>>  for alternative chain, does not have enough proof of work: 
[2018-04-10 08:57:57,539] [INFO] [sumokoind]>>>  expected difficulty: 5283587651
[2018-04-10 08:57:57,540] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:57.538442 [P2P9][45.77.91.22:19733 OUT]Block verification failed, dropping connection
[2018-04-10 08:57:57,540] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:57.538442 [P2P9]IP 45.77.91.22 fail score=1
[2018-04-10 08:57:58,459] [INFO] [sumokoind]>>> MARK   {3} {p1} 2018-04-10 08:57:58.458031 [abstract_tcp_server2.inl+271 ::save_dbg_log]  connection type RPC 127.0.0.1:19734 <--> 127.0.0.1:3521
[2018-04-10 08:57:58,460] [INFO] [sumokoind]>>> 
[2018-04-10 08:57:58,750] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:58.750388 [P2P7][173.19.192.56:19733 OUT]Sync data returned a new top block candidate: 116522 -> 118519 [Your node is 1997 blocks (5 days) behind]
[2018-04-10 08:57:58,752] [INFO] [sumokoind]>>> SYNCHRONIZATION started
[2018-04-10 08:57:58,753] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:58.750388 [P2P7]Remote blockchain height: 118519, id: <0f8d988dd01e76bcd7de3b6a67df6dcee4a321d2ec1dd54e793b814bd28e41cf>
[2018-04-10 08:57:58,753] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:58.750388 [P2P7][173.19.192.56:19733 OUT] COMMAND_HANDSHAKE INVOKED OK
[2018-04-10 08:57:58,755] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:58.751384 [P2P8]Connecting to 71.179.177.183:19733(white=0, last_seen: d0.h0.m0.s9)...
[2018-04-10 08:57:58,831] [INFO] [sumokoind]>>> MARK   {4} {p1} 2018-04-10 08:57:58.830625 [abstract_tcp_server2.inl+271 ::save_dbg_log]  connection type P2P 10.100.1.113:3522 <--> 71.179.177.183:19733
[2018-04-10 08:57:58,832] [INFO] [sumokoind]>>> 
[2018-04-10 08:57:59,151] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:59.149994 [P2P6][71.179.177.183:19733 OUT]Sync data returned a new top block candidate: 116522 -> 118519 [Your node is 1997 blocks (5 days) behind]
[2018-04-10 08:57:59,151] [INFO] [sumokoind]>>> SYNCHRONIZATION started
[2018-04-10 08:57:59,153] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:59.149994 [P2P6]Remote blockchain height: 118519, id: <0f8d988dd01e76bcd7de3b6a67df6dcee4a321d2ec1dd54e793b814bd28e41cf>
[2018-04-10 08:57:59,154] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:59.151000 [P2P6][71.179.177.183:19733 OUT] COMMAND_HANDSHAKE INVOKED OK
[2018-04-10 08:57:59,543] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:59.544539 [P2P6][173.19.192.56:19733 OUT]-->>NOTIFY_REQUEST_GET_OBJECTS: blocks.size()=10, txs.size()=0requested blocks count=10 / 10
[2018-04-10 08:57:59,562] [INFO] [sumokoind]>>> 2018-Apr-10 08:57:59.562552 [P2P9][71.179.177.183:19733 OUT]-->>NOTIFY_REQUEST_GET_OBJECTS: blocks.size()=10, txs.size()=0requested blocks count=10 / 10
[2018-04-10 08:58:00,132] [INFO] [sumokoind]>>> 2018-Apr-10 08:58:00.133261 [P2P6][71.179.177.183:19733 OUT]Got NEW BLOCKS inside of handle_response_get_objects: size: 10
[2018-04-10 08:58:00,134] [INFO] [sumokoind]>>> 2018-Apr-10 08:58:00.133261 [P2P6]block_batches: 2
[2018-04-10 08:58:00,135] [INFO] [sumokoind]>>> 2018-Apr-10 08:58:00.133261 [P2P6]Skipping prepare blocks. New blocks don't belong to chain.
[2018-04-10 08:58:00,177] [INFO] [sumokoind]>>> 2018-Apr-10 08:58:00.177269 [P2P6]Block with id: 
[2018-04-10 08:58:00,178] [INFO] [sumokoind]>>>  for alternative chain, does not have enough proof of work: 
[2018-04-10 08:58:00,180] [INFO] [sumokoind]>>>  expected difficulty: 5283587651
[2018-04-10 08:58:00,181] [INFO] [sumokoind]>>> 2018-Apr-10 08:58:00.178268 [P2P6][71.179.177.183:19733 OUT]Block verification failed, dropping connection
[2018-04-10 08:58:00,183] [INFO] [sumokoind]>>> 2018-Apr-10 08:58:00.178268 [P2P6]IP 71.179.177.183 fail score=1
[2018-04-10 08:58:02,832] [INFO] [sumokoind]>>> 2018-Apr-10 08:58:02.833693 [P2P9][173.19.192.56:19733 OUT]Got NEW BLOCKS inside of handle_response_get_objects: size: 10
[2018-04-10 08:58:02,834] [INFO] [sumokoind]>>> 2018-Apr-10 08:58:02.833693 [P2P9]block_batches: 2
[2018-04-10 08:58:02,834] [INFO] [sumokoind]>>> 2018-Apr-10 08:58:02.833693 [P2P9]Skipping prepare blocks. New blocks don't belong to chain.
[2018-04-10 08:58:02,881] [INFO] [sumokoind]>>> 2018-Apr-10 08:58:02.882727 [P2P9]Block with id: 
[2018-04-10 08:58:02,882] [INFO] [sumokoind]>>>  for alternative chain, does not have enough proof of work: 
[2018-04-10 08:58:02,884] [INFO] [sumokoind]>>>  expected difficulty: 5283587651
[2018-04-10 08:58:02,884] [INFO] [sumokoind]>>> 2018-Apr-10 08:58:02.882727 [P2P9][173.19.192.56:19733 OUT]Block verification failed, dropping connection
[2018-04-10 08:58:02,884] [INFO] [sumokoind]>>> 2018-Apr-10 08:58:02.882727 [P2P9]IP 173.19.192.56 fail score=1
[2018-04-10 08:58:08,454] [INFO] [sumokoind]>>> MARK   {3} {p1} 2018-04-10 08:58:08.454203 [abstract_tcp_server2.inl+271 ::save_dbg_log]  connection type RPC 127.0.0.1:19734 <--> 127.0.0.1:3525
[2018-04-10 08:58:08,457] [INFO] [sumokoind]>>>

**Comment by curie-kief** [comment]
@bryster99 That's our fork height. You need to update your sumokoind to 0.3

**Comment by bryster99** [comment]
@curei-kief  Thanks for the comment, but I have already updated sumokoind. When launching sumokoind from the windows powershell I can type 'help' and get this:
"Sumokoin 'Aomori' (v0.3.0.0-release)"
Is there a version beyond that? I have done everything I can think of to get this running again. Uninstall, reboot, reinstall, etc. 
Any other suggestions or debug info I can provide that would help? In the powershell it just keeps repeating:
2018-Apr-12 08:06:33.171977 [P2P6][87.99.89.39:19733 OUT]Sync data returned a new top block candidate: 116522 -> 119181 [Your node is 2659 blocks (7 days) behind]
SYNCHRONIZATION started
2018-Apr-12 08:07:09.052847 [P2P5][2.63.37.165:19733 OUT]Sync data returned a new top block candidate: 116522 -> 119181 [Your node is 2659 blocks (7 days) behind]
SYNCHRONIZATION started

**Comment by bryster99** [comment]
Tried deleting the imdb database one more time after uninstalling, rebooting and reinstalling. This time it synced all the way. So problem solved. Thanks!

**Comment by DrMaqueo** [comment]
I had this issue reported in GUI-Wallet, but got no help there ... but I tried something and worked. I downloaded the binaries "Aomori" (https://github.com/sumoprojects/sumokoin/releases/download/v0.3.0.0/sumokoin.win.x64.v0-3-0-0.zip)

In there you have sumo-blockchain-import.exe

I started downloading the raw blockchain, to try to rebuild the database faster, but it turned out I did not need to use it.

Checking the --help from the exe, I found --pop-blocks arg (=0) Remove blocks from end of blockchain

Since it could not update past 116521, I decided to pop from the end 5 blocks
PS C:\Sumokoin_GUI_Wallet-v0.0.3-w64\Resources\bin> .\sumo-blockchain-import.exe --pop-blocks 5
with output (just 2 last lines)
2018-Apr-12 19:27:10.767491 height: 116521
2018-Apr-12 19:27:12.091431 height: 116516

NOW, I went ahead and started the GUI Wallet, and voilá ... now is synchronizing perfectly. It seems something happened to the database at the time of the fork, and deleting the last blocks fixed the problem. You can try deleting just one or two, but five worked out for me.

I hope it helps ... Have fun

**Comment by quangvu3** [comment]
If you don't mind using `sumo-blockchain-import`, you can always download the latest blockchain raw file from:

https://blockchain.sumokoin.org/blockchain.raw

And import the blockchain with the command:

```
sumo-blockchain-import --input-file /path/to/blockchain.raw
```

You can also disable verification to speed up the importing process with:

```
sumo-blockchain-import --input-file /path/to/blockchain.raw --verify 0
```

**Comment by mjf2233** [comment]
Hello, I am having this same issue. I'm not a programmer. Where can i find the imdb database so I can delete it? Thanks

**Comment by quangvu3** [comment]
On Windows:

`C:\ProgramData\sumokoin\lmdb`

On Mac/Linux (at your Home directory):

`~\sumokoin\lmdb`

**Comment by mjf2233** [comment]
I don't see a ProgramData folder in my C: drive for some reason

**Comment by mjf2233** [comment]
got it. Thank you! Everything syncing now.

**Comment by namsur1234** [comment]
Hey guys, thanks for all the tips here! I had the same issue. When I went to pop out the extra blocks causing the issue, I found I did not remove enough the first time. So make sure you remove enough blocks to get you to 116519 or 116520 before you restart the daemon to attempt syncing.

**Comment by Janjanjanjajaja** [comment]
Hey Guys, i do not have a p2p bin file or an IMDB file in my sumokoin folder any idea what  i could do to get the wallet to sync again? Ps: Not a programmer

**Comment by kinderheim511** [comment]
I'm just here to thank quangvu3 for his efforts.

I imported the blockchain and it's working.

**Comment by tankmodz** [comment]
@Janjanjanjajaja for MAC
IF YOU ARE STUCK LIKE I WAS SYNCING THE BLOCKCHAIN ON MAC HIGH SIERRA
1) Open finder, look for (Macintosh HD) aka your hard drive.
2) Look for (Users), open it and find your profile you are signed as.
3) Now press on your keyboard (Shift, Command, . ) this will show hidden files
4) You will see a folder called (.sumokoin) open it.
5) You will see (Imdb) and (p2pstate.bin) delete both.
6) Open wallet now you will re-sync the whole blockchain

**Comment by bassjobsen** [comment]
@quangvu3 i tried your solutions, but it doesn't seems to work; why does it switch between days behind and ahead?

```
7 -> 145866 [Your node is 1419 blocks (3 days) behind]
[23:13:11] [INFO] [sumokoind]>>> SYNCHRONIZATION started
[23:13:27] [ERROR] [sumokoind]>>> 2018-Jun-25 23:13:27.690959 [P2P5]ERROR /home/bass/sumokoin/src/cryptonote_core/cryptonote_format_utils.cpp:102 Failed to parse transaction from blob
[23:13:56] [INFO] [sumokoind]>>> 2018-Jun-25 23:13:56.641538 [P2P5][188.216.66.117:19733 OUT]Sync data returned a new top block candidate: 144447 -> 144326 [Your node is 121 blocks (0 days) ahead]
[23:13:56] [INFO] [sumokoind]>>> SYNCHRONIZATION started
[23:14:29] [INFO] [sumokoind]>>> 2018-Jun-25 23:14:29.103168 [P2P6][72.15.139.135:19733 OUT]Sync data returned a new top block candidate: 144447 -> 116525 [Your node is 27922 blocks (77 days) ahead]
[23:14:29] [INFO] [sumokoind]>>> SYNCHRONIZATION started
[23:15:05] [INFO] [sumokoind]>>> 2018-Jun-25 23:15:05.737338 [P2P7][211.108.144.210:19733 OUT]Sync data returned a new top block candidate: 144447 -> 165005 [Your node is 20558 blocks (57 days) behind]
[23:15:05] [INFO] [sumokoind]>>> SYNCHRONIZATION started
[23:17:49] [INFO] [sumokoind]>>> 2018-Jun-25 23:17:49.473659 [P2P2][139.99.40.69:19733 OUT]Sync data returned a new top block candidate: 144447 -> 166223 [Your node is 21776 blocks (60 days) behind]
[23:17:49] [INFO] [sumokoind]>>> SYNCHRONIZATION started
[23:18:23] [INFO] [sumokoind]>>> 2018-Jun-25 23:18:23.652709 [P2P4][88.95.24.5:19733 OUT]Sync data returned a new top block candidate: 144447 -> 145867 [Your node is 1420 blocks (3 days) behind]
[23:18:23] [INFO] [sumokoind]>>> SYNCHRONIZATION started
[23:18:33] [ERROR] [sumokoind]>>> 2018-Jun-25 23:18:33.830750 [P2P0]ERROR /home/bass/sumokoin/src/cryptonote_core/cryptonote_format_utils.cpp:102 Failed to parse transaction from blob
[23:18:58] [INFO] [sumokoind]>>> 2018-Jun-25 23:18:58.517692 [P2P6][173.17.216.19:19733 OUT]Sync data returned a new top block candidate: 144447 -> 145867 [Your node is 1420 blocks (3 days) behind]
[23:18:58] [INFO] [sumokoind]>>> SYNCHRONIZATION started
[23:19:33] [INFO] [sumokoind]>>> 2018-Jun-25 23:19:33.452974 [P2P9][1.54.78.95:19733 OUT]Sync data returned a new top block candidate: 144447 -> 165005 [Your node is 20558 blocks (57 days) behind]
```

**Comment by technics67** [comment]
I ve tried;

- delete p2pstate.bin
-uninstall whole program and delete data folder
- tried to pop 5 blocks 100 blocks etc..

nothing fixed...

can anyone suggest another method ?

here is the last part of the log file which repeats itself...

[2018-06-27 15:58:50,144] [INFO] [sumokoind]>>> 2018-Jun-27 15:58:50.144418 [P2P7][87.229.116.69:19733 OUT]Sync data returned a new top block candidate: 165005 -> 144447 [Your node is 20558 blocks (57 days) ahead]
[2018-06-27 15:58:50,161] [INFO] [sumokoind]>>> SYNCHRONIZATION started
[2018-06-27 15:58:53,273] [INFO] [sumokoind]>>> 2018-Jun-27 15:58:53.272676 [P2P7][203.149.21.36:19733 OUT]Sync data returned a new top block candidate: 165005 -> 144447 [Your node is 20558 blocks (57 days) ahead]
[2018-06-27 15:58:53,293] [INFO] [sumokoind]>>> SYNCHRONIZATION started
[2018-06-27 15:58:56,167] [INFO] [sumokoind]>>> 2018-Jun-27 15:58:56.166986 [P2P9][92.53.79.124:19001 OUT]Sync data returned a new top block candidate: 165005 -> 146403 [Your node is 18602 blocks (51 days) ahead]
[2018-06-27 15:58:56,186] [INFO] [sumokoind]>>> SYNCHRONIZATION started
[2018-06-27 15:59:25,535] [INFO] [sumokoind]>>> 2018-Jun-27 15:59:25.534768 [P2P8][69.197.128.74:19733 OUT]Sync data returned a new top block candidate: 165005 -> 146403 [Your node is 18602 blocks (51 days) ahead]
[2018-06-27 15:59:25,542] [INFO] [sumokoind]>>> SYNCHRONIZATION started

**Comment by tankmodz** [comment]
EVERYONE if you are still having problems it was a update at block 16500 you need to update the GUI apphttps://twitter.com/sumokoin/status/1009727370281054208

**Comment by tankmodz** [comment]
@technics67 you have same log as me UPDATE YOUR WALLET due to the upcoming hard fork you need to update.

**Comment by sumoprojects** [comment]
-- Resolved
